# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/05lab5/project_lab5/project_lab5.srcs/sources_1/ip/DataBuffer/DataBuffer.xci
# IP: The module: 'DataBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/05lab5/project_lab5/project_lab5.gen/sources_1/ip/DataBuffer/DataBuffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataBuffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/05lab5/project_lab5/project_lab5.gen/sources_1/ip/DataBuffer/DataBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/05lab5/project_lab5/project_lab5.srcs/sources_1/ip/DataBuffer/DataBuffer.xci
# IP: The module: 'DataBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/05lab5/project_lab5/project_lab5.gen/sources_1/ip/DataBuffer/DataBuffer.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/05lab5/project_lab5/project_lab5.gen/sources_1/ip/DataBuffer/DataBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
