# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/06lab6-7/lab06-07/lab06-07.srcs/sources_1/bd/cpu_wrapper/ip/cpu_wrapper_clk_wiz_0_0/cpu_wrapper_clk_wiz_0_0.xci
# IP: The module: 'cpu_wrapper_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/06lab6-7/lab06-07/lab06-07.gen/sources_1/bd/cpu_wrapper/ip/cpu_wrapper_clk_wiz_0_0/cpu_wrapper_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_wrapper_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/06lab6-7/lab06-07/lab06-07.gen/sources_1/bd/cpu_wrapper/ip/cpu_wrapper_clk_wiz_0_0/cpu_wrapper_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_wrapper_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/06lab6-7/lab06-07/lab06-07.gen/sources_1/bd/cpu_wrapper/ip/cpu_wrapper_clk_wiz_0_0/cpu_wrapper_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_wrapper_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/06lab6-7/lab06-07/lab06-07.srcs/sources_1/bd/cpu_wrapper/ip/cpu_wrapper_clk_wiz_0_0/cpu_wrapper_clk_wiz_0_0.xci
# IP: The module: 'cpu_wrapper_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/06lab6-7/lab06-07/lab06-07.gen/sources_1/bd/cpu_wrapper/ip/cpu_wrapper_clk_wiz_0_0/cpu_wrapper_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_wrapper_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/06lab6-7/lab06-07/lab06-07.gen/sources_1/bd/cpu_wrapper/ip/cpu_wrapper_clk_wiz_0_0/cpu_wrapper_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_wrapper_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/06lab6-7/lab06-07/lab06-07.gen/sources_1/bd/cpu_wrapper/ip/cpu_wrapper_clk_wiz_0_0/cpu_wrapper_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_wrapper_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
