# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/cpu_wrapper/cpu_wrapper.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_wrapper || ORIG_REF_NAME==cpu_wrapper} -quiet] -quiet

# IP: bd/cpu_wrapper/ip/cpu_wrapper_single_cycle_cpu_lab7_0_0/cpu_wrapper_single_cycle_cpu_lab7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_wrapper_single_cycle_cpu_lab7_0_0 || ORIG_REF_NAME==cpu_wrapper_single_cycle_cpu_lab7_0_0} -quiet] -quiet

# IP: bd/cpu_wrapper/ip/cpu_wrapper_clk_wiz_0_0/cpu_wrapper_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_wrapper_clk_wiz_0_0 || ORIG_REF_NAME==cpu_wrapper_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/thana/Second-Year/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/06lab6-7/lab06-07/lab06-07.gen/sources_1/bd/cpu_wrapper/cpu_wrapper_ooc.xdc
