# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/03lab3/part4/part4-project/part4-project.srcs/sources_1/ip/ila_data_out/ila_data_out.xci
# IP: The module: 'ila_data_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/03lab3/part4/part4-project/part4-project.gen/sources_1/ip/ila_data_out/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/03lab3/part4/part4-project/part4-project.gen/sources_1/ip/ila_data_out/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/03lab3/part4/part4-project/part4-project.gen/sources_1/ip/ila_data_out/ila_data_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/03lab3/part4/part4-project/part4-project.srcs/sources_1/ip/ila_data_out/ila_data_out.xci
# IP: The module: 'ila_data_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/03lab3/part4/part4-project/part4-project.gen/sources_1/ip/ila_data_out/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/03lab3/part4/part4-project/part4-project.gen/sources_1/ip/ila_data_out/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/03lab3/part4/part4-project/part4-project.gen/sources_1/ip/ila_data_out/ila_data_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_data_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
