# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/04lab4/part3/project_1/project_1.srcs/sources_1/ip/fifo_bram/fifo_bram.xci
# IP: The module: 'fifo_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/04lab4/part3/project_1/project_1.gen/sources_1/ip/fifo_bram/fifo_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_bram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/04lab4/part3/project_1/project_1.srcs/sources_1/ip/fifo_bram/fifo_bram.xci
# IP: The module: 'fifo_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/04lab4/part3/project_1/project_1.gen/sources_1/ip/fifo_bram/fifo_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
