# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/04lab4/part2/project_2/project_2.srcs/sources_1/ip/blk_mem_ram/blk_mem_ram.xci
# IP: The module: 'blk_mem_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/04lab4/part2/project_2/project_2.gen/sources_1/ip/blk_mem_ram/blk_mem_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/04lab4/part2/project_2/project_2.srcs/sources_1/ip/blk_mem_ram/blk_mem_ram.xci
# IP: The module: 'blk_mem_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thana/HW-SYS-Lab/2110363-Hardware-Synthesis-Laboratory-I/04lab4/part2/project_2/project_2.gen/sources_1/ip/blk_mem_ram/blk_mem_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
